name: Docker Build and Push

on:
  push:
    branches:
      - main # Replace with your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build . -t iainttho/nk-connect:0.0.1-${{ github.run_number }} || exit 1
          docker tag iainttho/nk-connect:0.0.1-${{ github.run_number }} iainttho/nk-connect:latest || exit 1
          docker push iainttho/nk-connect:latest || exit 1
          docker push iainttho/nk-connect:0.0.1-${{ github.run_number }} || exit 1
        env:
          DOCKER_CLI_ACI: "1"
        working-directory: ./

      - name: Logout from Docker Hub
        run: docker logout
